use std::fs::File;
use std::io::Write;

// Student struct to hold student information
struct Student {
    name: String,
    matrix_number: String,
    department: String,
    level: u32,
}

impl Student {
    fn new(name: &str, matrix_number: &str, department: &str, level: u32) -> Student {
        Student {
            name: name.to_string(),
            matrix_number: matrix_number.to_string(),
            department: department.to_string(),
            level,
        }
    }

    fn get_department_level(&self) -> String {
        format!("{} {}", self.department, self.level)
    }
}

fn main() {
    // Create student data array
    let students = vec![
        Student::new("Oluchi Morei", "ACC10211111", "Accounting", 300),
        Student::new("Adams Allyn", "EC01010101", "Economics", 100),
        Student::new("Sianna Bolade", "CSC1032828", "Computer", 200),
        Student::new("Adekunie Gold", "EE11020202", "Electrical", 200),
        Student::new("Blanca Edemoh", "MEE10002001", "Mechanical", 100),
    ];

    // Display students in console
    display_students_console(&students);
    
    // Save students to file
    save_students_to_file(&students);
    
    println!("\n✅ Student data successfully processed!");
}

fn display_students_console(students: &[Student]) {
    println!("{}\n", "=".repeat(70));
    println!("{:^70}", "PAU STUDENT MANAGEMENT INFORMATION SYSTEM (PAU-SMIS)");
    println!("{}\n", "=".repeat(70));
    
    println!("{:<20} {:<15} {:<20}", "Student Name", "Matrix Number", "Department Level");
    println!("{:-<20} {:-<15} {:-<20}", "", "", "");
    
    for student in students {
        println!("{:<20} {:<15} {:<20}", 
                 student.name, 
                 student.matrix_number, 
                 student.get_department_level());
    }
    
    println!("\nTotal Students: {}", students.len());
}

fn save_students_to_file(students: &[Student]) {
    let mut file = File::create("pau_smis_students.txt")
        .expect("Failed to create file");

    // Write header
    writeln!(file, "{}", "=".repeat(70)).expect("Failed to write to file");
    writeln!(file, "{:^70}", "PAU STUDENT MANAGEMENT INFORMATION SYSTEM (PAU-SMIS)").expect("Failed to write to file");
    writeln!(file, "{}", "=".repeat(70)).expect("Failed to write to file");
    writeln!(file).expect("Failed to write to file");
    
    // Write table header
    writeln!(file, "{:<20} | {:<15} | {:<20}", 
             "Student Name", "Matrix Number", "Department Level").expect("Failed to write to file");
    writeln!(file, "{:-<20}-+-{:-<15}-+-{:-<20}", 
             "", "", "").expect("Failed to write to file");
    
    // Write student data
    for student in students {
        writeln!(file, "{:<20} | {:<15} | {:<20}", 
                 student.name, 
                 student.matrix_number, 
                 student.get_department_level()).expect("Failed to write to file");
    }
    
    // Write footer
    writeln!(file).expect("Failed to write to file");
    writeln!(file, "{}", "=".repeat(70)).expect("Failed to write to file");
    writeln!(file, "Total Students: {}", students.len()).expect("Failed to write to file");
    writeln!(file, "Generated by PAU-SMIS").expect("Failed to write to file");
    
    println!("📁 Student records saved to 'pau_smis_students.txt'");
}

// Additional function to demonstrate reading from the file
fn display_file_info() {
    println!("\n📋 File Information:");
    println!("File created: pau_smis_students.txt");
    println!("Format: Text file with formatted student records");
    println!("Purpose: Official student data storage for PAU-SMIS");
}